const Map<String, String> ar = {
  'Home': 'الصفحة الرئيسية',
  'Inventory': 'المخزون',
  'Self management of inventory': 'الإدارة الذاتية للمخزون',
  'you can enter, withdraw, and transfer the inventory alone':
      'يمكنك الدخول والسحب ونقل المخزون بمفردك',
  'control panel': 'لوحة التحكم',
  'call customer care': 'اتصل بخدمة العملاء',
  'you can add your inventory by customer care':
      'يمكنك إضافة المخزون الخاص بك عن طريق خدمة العملاء',
  'call now': 'اتصل الان',
  'Monitoring': 'المراقبة',
  'Account Monitoring': 'مراقبة الحساب',
  'Analysis of your inventory can be found':
      'يمكن العثور على تحليل المخزون الخاص بك',
  'view': 'عرض',
  'Start Adding Warehouse': 'ابدأ بإضافة المستودع',
  'Warehouse Management': 'إدارة المستودعات',
  'You can add warehouse and view warehouse list':
      'يمكنك إضافة مستودع وعرض قائمة المستودعات',
  'Management Now': 'الإدارة الآن',
  'operations': 'العمليات',
  'Enter Inventory': 'أدخل المخزون',
  'Your inventory can be added to the warehouse':
      'يمكن إضافة المخزون الخاص بك إلى المستودع',
  'Enter stock Now': 'أدخل المخزون الآن',
  'Withdrawal of inventory': 'سحب المخزون',
  'You can withdraw your inventory from the warehouse':
      'يمكنك سحب المخزون الخاص بك من المستودع',
  'Withdrawal Stock Now': 'سحب لمخزون الآن',
  'Transfer Inventory': 'نقل المخزون',
  'You can transfer your inventory to the anther warehouse':
      'يمكنك نقل المخزون الخاص بك إلى المستودع الآخر',
  'Transfer Stock Now': 'نقل المخزون الآن',
  'My Warehouse': 'مستودعاتي',
  'Add Warehouse': 'إضافة مستودع',
  'View map': 'عرض الخريطة',
  'Address': 'العنوان',
  'Price': 'السعر',
  'Temperature': 'درجة حرارة',
  'Used': 'المستخدم',
  'Reserved Space': 'المساحة المحجوزة',
  'Expired WH': 'تنتهي صلاحيته',
  'Upgrade Space': 'زيادة المساحة',
  'Dry': 'جاف',
  'Cold': 'بارد',
  'Freezing': 'متجمد',
  'Add New Warehouse': 'إضافة مستودع جديد',
  'Properties of the warehouse to be added to the warehouse list':
      'خصائص المستودع المراد إضافتها إلى قائمة المستودعات',
  'Space Needed': 'المساحة المطلوبة',
  '10 M²  = 12 wooden pallets': '10 م² = 12 طبلية خشبي',
  'Booking Date': 'تاريخ الحجز',
  'From': 'من',
  'To': 'الى',
  'Stock Type': 'نوع المخزون',
  'Continue': 'استمرار',
  'What type of material ?': 'ما نوع المادة؟',
  'Foodstuffs': 'مواد الغذائية',
  'Chemicals': 'مواد كيميائية',
  'Electrical materials': 'مواد كهربائية',
  'other': 'اخرى',
  'Type': 'النوع',
  'space': 'المساحة',
  'M²': 'م²',
  'Stock ID': 'معرف المخزون',
  'View Details': 'عرض التفاصيل',
  'Subscription ID': 'معرف الإشتراك',
  'Barcode': 'الباكود',
  'Unit': 'الوحدة',
  'The number': 'العدد',
  'Stock description': 'وصف المخزون',
  'Inventory Warehouse': 'مستودع المخزون',
  'Stock Inventory': 'المخزون',
  'Stock Warehouse': 'مستودع المخزون',
  'Enter Stock': 'أدخل مخزون',
  'Add Stock': 'إضافة مخزون',
  'Photo Gallery': 'معرض الصور',
  'Camera': 'كاميرا',
  'Name stock': 'اسم المخزون',
  'Barcode scanner (optional)': 'ماسح الباركود (اختياري)',
  'The space to be enter': 'المساحة المراد دخولها',
  'Note: The stock to be stored must be the same as the stored stock':
      'ملحوظة: المخزون المراد تخزينه يجب أن يكون نفس المخزون المخزن',
  'Stock transfer': 'نقل المخزون',
  'Description': 'الوصف',
  'The space to be transfer': 'المساحة المراد نقلها',
  'Transfer to': 'نقل الى',
  'Warehouse name': 'اسم المستودع',
  'Transfer': 'نقل',
  'Confirm location': 'تأكيد الموقع',
  'Withdraw Now': 'سحب الآن',
  'With packaging': 'مع التغليف',
  'Select a delivery location': 'حدد موقع التسليم',
  'With delivery to a new location': 'مع التسليم إلى موقع جديد',
  'Other services': 'خدمات أخرى',
  'Default: Receive from warehouse': 'الافتراضي: الاستلام من المستودع',
  'The space to be withdrawn': 'المساحة المراد سحبها',
  'Withdrawal date': 'تاريخ السحب',
  'Stock withdrawal': 'سحب المخزون',
  'Enter Now': 'أدخل الأن',
  'date': 'التاريخ',
  'Transfer now': 'نقل الآن',
  'Address WH': 'عنوان المستودع',
  'Locate inventory': 'حدد موقع المخزون',
  'Select the warehouse to continue': 'حدد المستودع للمتابعة',
  'continue': 'استمرار',
  'Search Location': 'بحث عن موقع',
  'change Inventory location': 'تغير موقع المخزون',
  'Locate inventory on the map': 'تحديد موقع المخزون على الخريطة',
  'Click on any location on the map to choose the inventory location':
      'قم بالضغط على اي موقع على الخريطة للاختيار موقع المخزون',
  'cancel': 'إلغاء',
  'Please select a inventory location': 'الرجاء تحديد موقع المخزون',
  'Locate your inventory on the map now':
      'قم بتحديد موقع المخزون على الخريطة الان',
  'Ok': 'موافق',
  'capacity': 'السعة',
  'phone': 'رقم الهاتف',
  'price Per Meter': 'السعر لكل متر',
  'Total price': 'السعر الاجمالي',
  'You have selected the inventory location': 'لقد قمت بتحديد موقع المخزون',
  'Confirm the operation': 'تأكيد العملية',
  'Do you want to store in the warehouse': 'هل تريد التخزين في المخزن',
  '?': '؟',
  'Warehouse details': 'تفاصيل المستودع',
  'the cost': 'التكلفة',
  'distance': 'المسافة',
  'Warehouse location': 'موقع المستودع',
  'Inventory location': 'موقع المخزون',
  'the map': 'الخريطة',
  'km': 'كم',
  'SR': 'ريال سعودي',
  'Pay now': 'ادفع الآن',
  'Warehouse rental period': 'فترة تأجير المستودعات',
  'Warehouse Features': 'مميزات المستودع',
  'Warehouse ID': 'معرف المستودع',
  'Invoice info': 'معلومات الفاتورة',
  'INVOICE': 'فاتورة',
  'invoice': 'فاتورة',
  'done': 'تم',
  'Profile': 'الملف الشخصي',
  'Settings': 'الاعدادات',
  'Personal Information': 'المعلومات شخصية',
  'Username': 'اسم المستخدم',
  'Business Name': 'الاسم التجاري',
  'Business Competence': 'الكفاءة التجارية',
  'Subscription Ends': 'ينتهي الاشتراك',
  'Transactions': 'المعاملات',
  'Enter inventory': 'أدخل المخزون',
  'Enters': 'ادخال',
  'Withdrawal': 'سحب',
  'Withdrawals': 'السحب',
  'All Transactions': 'كل المعاملات',
  'Transaction ID': 'رقم العملية',
  'Quantity': 'الكمية',
  'Under Review': 'قيد المراجعة',
  'Accepted': 'مقبول',
  'Rejected': 'مرفوض',
  'Share': 'مشاركة',
  'Please enter the date': 'الرجاء إدخال التاريخ',
  'Please enter the space you need': 'الرجاء إدخال المساحة التي تحتاجها',
  'Contact Us': 'اتصل بنا',
  'Language': 'اللغه',
  'Delete Account': 'حذف الحساب',
  'Terms & Conditions': 'الشروط والاحكام',
  'Sign Out': 'تسجيل خروج',
  '* Of course, here is a definition of each point in the policy and terms of use of the mediation application between store owners and tenants:':
      'وبالطبع هنا تعريف لكل نقطة في سياسة وشروط استخدام تطبيق الوساطة بين أصحاب المتاجر والمستأجرين',
  '1. Application definition:\n\n - The mediation application is an electronic platform that acts as an intermediary between store owners and tenants.\n\n The app allows warehouse owners to view information about their storage space and the services they provide, while tenants can search for suitable storage space and make reservations.\n\n 2. Registration and accounts:\n\n - All users must register their accounts in the application using personal information such as name and email address.\n\n - Users must provide accurate and correct information during the registration process to ensure smooth and effective communication.\n\n - Users must keep their account information confidential and not share it with any third party.\n\n 3. Rights and obligations:\n\n Store owners are obligated to provide accurate information about the store and the services provided, including prices and time frames.\n\n - Renters are obligated to comply with the terms and conditions applicable in the application, including the cancellation and compensation policy.\n\n 4. Booking and payment:\n\n - Tenants must make a reservation through the application and with the approval of the store owners for the reservation. Payment must be made via the payment methods available in the application, such as credit cards or electronic payment methods.\n\n - A commission will be collected from tenants when using the application services and will be paid to the store owners.\n\n 5. Insurance and liability:\n\n - The application may provide options for shipping and storage insurance. Users are responsible for choosing the insurance appropriate to their needs.\n\n - The application is not responsible for any damages or losses that occur during the use of the services provided on the platform.\n\n 6. Booking cancellation and refund:\n\n - Users must adhere to the reservation cancellation policy applicable in the application. A cancellation fee will apply to renters if a reservation is canceled after a certain period.\n\n 7. privacy policy:\n\n - The privacy policy outlines how we collect and use personal information in the application. Users must read and understand the privacy policy applicable to the application.\n\n 8. Account Termination:\n\n - The application has the right to terminate the account of any user who violates the terms and conditions or causes inconvenience to others. Account termination may include, for example, temporary or permanent suspension.\n\n 9. Change of terms and conditions:\n\n - The application may change the terms and conditions of use, and users will be notified of any potential changes through notifications or updates in the application.\n\n 10. Contact us:\n\n - Users should contact the app support team in case of any queries or issues while using the app.\n\n 11. Modify or cancel your reservation:\n\n - Renters can modify or cancel their reservations in accordance with the reservation modification and cancellation policy applicable in the application. A cancellation fee may apply to renters if a reservation is canceled after a certain period.\n\n 12. User Reviews:\n\n - Users can provide ratings and reviews for store owners and their services. Users must provide honest and constructive reviews to enhance the quality of the Services.\n\n 13. Information integrity:\n\n - Users should be careful when sharing sensitive information such as credit card information via the app. The application must have security measures to protect personal information.\n\n 14. Rulers violations:\n\n - Users must report any violations of the terms and conditions or security violations on the application. These reports will be investigated and necessary measures will be taken.\n\n 15. Local laws:\n\n - Users must comply with local laws and regulations applicable in their area when using the Application Services.\n\n 16. Compensation and responsibilities of both parties:\n\n - Tenants and store owners must reach a clear agreement regarding compensation in the event of any damages or losses occurring while using the services. The application is not responsible for any claims in this regard.\n\n 17. Cooperation with the authorities:\n\n - The application must cooperate with local authorities regarding investigations and information requested from it.\n\n 18. NOTICES AND COMMUNICATIONS:\n\n - The Application may send notifications and communications to users via email, text messages or other means for purposes such as platform updates and promotion of services.\n\n 19. Application of laws and disputes:\n\n In the event of any dispute between tenants and warehouse owners, the parties should try to resolve the dispute amicably first through communication and negotiation. If the dispute is not resolved amicably, the parties can resort to local laws and judicial system to resolve the dispute.\n\n 20. Updated policy and terms:\n\n The application development company reserves the right to amend or update the Terms and Conditions of Use. Users will be notified of any potential changes through the contact methods in the application':
      'السياسة وشروط الاستخدام لتطبيق الوساطة بين أصحاب المخازن والمستأجرين:تعريف التطبيق: \n\n   - تطبيق الوساطة هو منصة إلكترونية تعمل كوسيط بين أصحاب المخازن والمستأجرين. يتيح التطبيق لأصحاب المخازن عرض معلومات حول مساحة تخزينهم والخدمات التي يقدمونها، بينما يمكن للمستأجرين البحث عن مساحة تخزين مناسبة وإجراء حجوزاتالتسجيل والحسابات: \n\n   - يجب على جميع المستخدمين تسجيل حساباتهم في التطبيق باستخدام معلومات شخصية مثل الاسم وعنوان البريد الإلكتروني. \n\n - يجب على المستخدمين تقديم معلومات دقيقة وصحيحة أثناء عملية التسجيل لضمان تواصل سلس وفعال.  \n\n - يجب على المستخدمين الحفاظ على سرية معلومات حسابهم وعدم مشاركتها مع أي طرف ثالث.الحقوق والالتزامات:  \n\n - أصحاب المخازن ملزمون بتوفير معلومات دقيقة حول المخزن والخدمات المقدمة، بما في ذلك الأسعار والمدى الزمني.  \n\n - المستأجرين ملزمون بالامتثال للشروط والأحكام المعمول بها في التطبيق، بما في ذلك سياسة الإلغاء والتعويضات.الحجز والدفع:  \n\n - المستأجرين يجب أن يقوموا بإجراء الحجز عبر التطبيق وبموافقة أصحاب المخازن على الحجز.  \n\n - الدفع يجب أن يتم عبر وسائل الدفع المتاحة في التطبيق، مثل البطاقات الائتمانية أو طرق الدفع الإلكترونية  \n\n - سيتم تحصيل عمولة من المستأجرين عند استخدام خدمات التطبيق وسيتم دفعها إلى أصحاب المخازن.التأمين والمسؤولية:  \n\n - التطبيق قد يوفر خيارات للتأمين على الشحن والتخزين. يتحمل المستخدمون مسؤولية اختيار التأمين المناسب لاحتياجاتهم  \n\n - التطبيق ليس مسؤولًا عن أية أضرار أو خسائر تحدث خلال استخدام الخدمات المقدمة على المنصةإلغاء الحجز واسترداد الأموال: \n\n - يجب على المستخدمين الالتزام بسياسة إلغاء الحجز المعمول بها في التطبيق. سيتم تطبيق رسوم إلغاء على المستأجرين إذا تم إلغاء الحجز بعد فترة معينة.سياسة الخصوصية:  \n\n - سياسة الخصوصية تحدد كيفية جمع واستخدام المعلومات الشخصية في التطبيق. يجب على المستخدمين قراءة وفهم سياسة الخصوصية المعمول بها في التطبيق.إنهاء الحساب:  \n\n - يحق للتطبيق إنهاء حساب أي مستخدم ينتهك الشروط والأحكام أو يسبب إزعاجًا للآخرين. إنهاء الحساب قد يشمل الإيقاف المؤقت أو الدائم على سبيل المثال: \n\n تغيير الشروط والأحكام  \n\n - يمكن للتطبيق تغيير شروط وأحكام الاستخدام، وسيتم إشعار المستخدمين بأي تغييرات محتملة من خلال إشعارات أو تحديثات في التطبيق. \n\n الاتصال بنا : \n\n - يجب على المستخدمين الاتصال بفريق دعم التطبيق في حالة وجود أي استفسارات أو مشكلات أثناء استخدام التطبيق: \n\n تعديل أو إلغاء الحجز  \n\n - المستأجرين يمكنهم تعديل أو إلغاء حجوزاتهم وفقًا لسياسة تعديل وإلغاء الحجز المعمول بها في التطبيق. قد يتم تطبيق رسوم إلغاء على المستأجرين إذا تم إلغاء الحجز بعد فترة معينة:\n\n  تقييمات المستخدمين:  \n\n - المستخدمين يمكنهم تقديم تقييمات ومراجعات لأصحاب المخازن وخدماتهم. يجب على المستخدمين تقديم تقييمات صادقة وبناءة لتعزيز جودة الخدمات \n\n سلامة المعلومات : \n\n - يجب على المستخدمين توخي الحذر عند مشاركة معلومات حساسة مثل معلومات بطاقات الائتمان عبر التطبيق. التطبيق يجب أن يتوفر على إجراءات أمان لحماية المعلومات الشخصية.انتهاكات الحكام: \n\n  - يجب على المستخدمين الإبلاغ عن أي انتهاكات للشروط والأحكام أو مخالفات أمان على التطبيق. سيتم التحقيق في هذه البلاغات واتخاذ الإجراءات اللازمة \n\n قوانين محلية :  \n\n -. يجب على المستخدمين الامتثال للقوانين واللوائح المحلية المعمول بها في منطقتهم عند استخدام خدمات التطبيقتعويضات ومسؤوليات الطرفين: \n\n  - يجب على المستأجرين وأصحاب المخازن التوصل إلى اتفاق واضح بشأن التعويضات في حالة وقوع أي أضرار أو خسائر أثناء استخدام الخدمات. التطبيق غير مسؤول عن أية مطالبات في هذا الصدد \n\n الإشعارات والاتصالات: \n\n  - يمكن للتطبيق إرسال إشعارات واتصالات للمستخدمين عبر البريد الإلكتروني أو رسائل نصية أو وسائل أخرى لأغراض مثل تحديثات المنصة وترويج الخدمات \n\n  تطبيق القوانين والنزاعاتفي حالة وجود أي نزاع بين المستأجرين وأصحاب المخازن: \n\n يجب على الأطراف أن تحاول حل النزاع بشكل ودي أولاً عبر التواصل والتفاوضفي حالة عدم تسوية النزاع بشكل ودي، يمكن للأطراف اللجوء إلى القوانين والنظام القضائي المحلي لحل النزاعتحديث السياسة والشروط :\n\n تحتفظ شركة تطوير التطبيق بالحق في تعديل أو تحديث سياسة الحكام وشروط الاستخدام. سيتم إشعار المستخدمين بأي تغييرات محتملة من خلال وسائل الاتصال في التطبيق.',
  'Add Item': 'اضافة عنصر',
  'Transportation Fees': 'رسوم النقل',
  'Login': 'تسجيل الدخول',
  'Enter your email and password to access the warehouse':
      'أدخل بريدك الإلكتروني وكلمة المرور للوصول إلى المستودع',
  'Please enter Your Username': 'الرجاء إدخال اسم المستخدم',
  'email': 'البريد إلكتروني',
  'Please enter your password': 'الرجاء إدخال كلمة المرور',
  'password': 'كلمة المرور',
  "Don't Have Account ?  ": "ليس لديك حساب ؟  ",
  'Sign Up': 'تسجيل',
  'Enter your data to register in our warehouse':
      'أدخل بياناتك للتسجيل في مستودعاتنا',
  'please enter email': "الرجاء إدخال بريد الإلكتروني",
  'please enter password': 'الرجاء إدخال كلمة مرور',
  'Please use at least 8 characters': 'يُرجى استخدام 8 أحرف على الأقل',
  'Already have any account?  ': 'هل لديك أي حساب بالفعل ؟ ',
  'Complete your information': 'أكمل ادخال معلوماتك',
  'please enter your name': 'الرجاء ادخال الاسم',
  'Full Name': 'الاسم الكامل',
  'please enter business name': 'الرجاء إدخال الاسم التجاري',
  'please enter business competence': 'الرجاء إدخال الكفاءة التجارية',
  'please enter phone number': 'الرجاء إدخال رقم الهاتف',
  'please enter phone number 2': 'الرجاء إدخال رقم الهاتف 2',
  'Enter a correct number': 'أدخل رقما صحيحا',
  'Phone Number': 'رقم الهاتف ',
  'Phone Number 2': 'رقم الهاتف 2',
  'Complete': 'تم',
  'Terms & Condition': 'الشروط والأحكام',
  "I've read and agree to the terms and conditions of the privacy policy":
      "لقد قرأت ووافقت على شروط وأحكام سياسة الخصوصية",
  'Dhlez Warehouse Management System is a specialized system designed to simplify and improve warehouse operations and manage them efficiently':
      'نظام دهليز إلدارة المستودعات هو نظام متخصص ُيصمم لتبسيط وتحسين عمليات المستودعات وإدارتها بكفاءة باعتباره نموذًجا لألنظمة المتطورة في هذا المجال',
  'Are you sure you want to exit the application?':
      'هل أنت متأكد أنك تريد الخروج من التطبيق؟',
  'Exit': 'خروج',
  'Cancel': 'الغاء',
  'Stock Temperature': 'درجة حرارة المخزون',
  'Stock Brand': 'العلامة التجارية للمخزون',
  'Stock Barcode': 'باركود المخزون',
  'Stock capacity': 'سعة المخزون',
  'Upc stock': 'Upc المخزون',
  'Send subscription request successfully !': 'تم ارسال طلب الاشتراك بنجاح !',
  'Error Send subscription request!': 'خطأ في ارسال طلب الاشتراك !',
  'A new entry transaction request has been sent. Please wait for approval':
      'تم إرسال طلب معاملة ادخال جديده. يرجى الانتظار للحصول على الموافقة',
  'A new transfer transaction request has been sent. Please wait for approval':
      'تم إرسال طلب معاملة نقل جديده. يرجى الانتظار للحصول على الموافقة',
  'A new withdrawal transaction request has been sent. Please wait for approval':
      'تم إرسال طلب معاملة سحب جديده. يرجى الانتظار للحصول على الموافقة',
  '°C': 'درجة مئوية',
  'SAR/M2': 'ريال سعودي / م²',
  'SAR/M²': 'ريال سعودي / م²',
  'Cost': 'التكلفة',
  'The list is currently empty': 'القائمة فارغة حاليا',
  'No items found': 'لا يوجد عناصر',
  'Subscription status': 'حالة الاشتراك',
  'Payment status': 'حالة الدفع',
  'Paid': 'مدفوع',
  'UnPaid': 'غير مدفوع',
  'subscription inactive': 'الاشتراك غير فعال',
  'Please enter the description inventory': 'الرجاء إدخال وصف المخزون',
  'Description inventory': 'وصف المخزون',
  'warning': 'تنبيه',
  'please upload image': 'يرجى تحميل الصورة',
  'Confirm': 'تأكيد',
  'space required': 'المساحة المطلوبة',
  'Booking days': 'أيام الحجز المطلوبة',
  'select temperatures': 'حدد درجات الحرارة',
  'No dry temperatures': 'لا يوجد درجات حرارة جافة',
  'No cold Temperatures': 'لا يوجد درجات حرارة باردة',
  'No Freezing Temperatures': 'لا يوجد درجات حرارة متجمدة',
  'show transportation services': 'عرض خدمات النقل المتوفرة',
  'No transportation services': 'لا يوجد خدمات نقل',
  'View All Supported Categories': 'عرض جميع الاصناف المدعومة',
  'No Category': 'لا يوجد اصناف',
  'Please enter the required temperature': 'الرجاء إدخال درجة الحرارة المطلوبة',
  'days': 'ايام',
  'warehouse location': 'موقع المستودع',
  'The cost': 'التكلفة',
  'Warehouse Name': 'اسم المستودع',
  'per day': 'لكل يوم',
  'Send subscription request': 'ارسال طلب اشتراك',
  'Please select temperature': 'اختر درجة الحرارة',
  'please select warehouse': 'الرجاء اختيار المستودع',
  'Enter Warehouse': 'ادخال للمستودع',
  'Transfer Warehouse': 'نقل من المستودع',
  'Withdrawal Warehouse': 'سحب من المستودع',
  'Withdrawal Stock': 'سحب مخزون',
  'Transfer Stock': 'نقل مخزون',
  'Upload image': 'تحميل صورة',
  'ID of the inventory deliverer': 'هوية مرسل المخزون',
  'Inventory recipient ID': 'هوية مستلم المخزون',
  'Transfer date': 'تاريخ النقل',
  'Stock Name': 'اسم المخزون',
  'Enter date': 'تاريخ الادخال',
  'Call the following number for assistance': 'اتصل بالرقم التالي للمساعدة',
  'Terms & Condition Agreement': 'اتفاقية الشروط والأحكام',
  'Waiting for your review': 'في انتظار مراجعتك',
  'Preliminary Approval': 'مقبول مبدأيا',
  'Status Stock': 'حالة المخزون',
  'withdrawal': 'سحب',
  'enter': 'ادخال',
  'transfer': 'نقل',
  'Are you sure the approve entry?': 'هل أنت متأكد من الموافقة على الادخال؟',
  'Reject Reason': 'رفض السبب',
  'transaction accepted done': 'تم قبول المعاملة',
  'Completed Successfully !': 'تم بنجاح !',
  'Stock Details': 'تفاصيل المخزون',
  'stock accepted and entered': 'تم قبول المخزون وتخزينه',
  'Inventory does not match. Pending your review':
      'المخزون غير مطابق بانتظار مراجعتك',
  'stock not match, but entry approved':
      'المخزون غير متطابق، ولكن تمت الموافقة ادخاله',
  'stock not match. Entry rejected': 'المخزون غير متطابق. تم رفض الإدخال',
  'Entry rejected': 'تم رفض الإدخال',
  'Matching images': 'صور المطابقة',
  'Accept': 'قبول',
  'Are you sure the reject entry?': 'هل أنت متأكد من رفض الإدخال؟',
  'reject': 'رفض',
};
