const Map<String, String> ar = {
  'Home': 'الصفحة الرئيسية',
  'Inventory': 'المخزون',
  'Self management of inventory': 'الإدارة الذاتية للمخزون',
  'you can enter, withdraw, and transfer the inventory alone':
      'يمكنك الدخول والسحب ونقل المخزون بمفردك',
  'control panel': 'لوحة التحكم',
  'call customer care': 'اتصل بخدمة العملاء',
  'you can add your inventory by customer care':
      'يمكنك إضافة المخزون الخاص بك عن طريق خدمة العملاء',
  'call now': 'اتصل الان',
  'Monitoring': 'المراقبة',
  'Account Monitoring': 'مراقبة الحساب',
  'Analysis of your inventory can be found':
      'يمكن العثور على تحليل المخزون الخاص بك',
  'view': 'عرض',
  'Start Adding Warehouse': 'ابدأ بإضافة المستودع',
  'Warehouse Management': 'إدارة المستودعات',
  'You can add warehouse and view warehouse list':
      'يمكنك إضافة مستودع وعرض قائمة المستودعات',
  'Management Now': 'الإدارة الآن',
  'operations': 'العمليات',
  'Enter Inventory': 'أدخل المخزون',
  'Your inventory can be added to the warehouse':
      'يمكن إضافة المخزون الخاص بك إلى المستودع',
  'Enter stock Now': 'أدخل المخزون الآن',
  'Withdrawal of inventory': 'سحب المخزون',
  'You can withdraw your inventory from the warehouse':
      'يمكنك سحب المخزون الخاص بك من المستودع',
  'Withdrawal Stock Now': 'سحب لمخزون الآن',
  'Transfer Inventory': 'نقل المخزون',
  'You can transfer your inventory to the anther warehouse':
      'يمكنك نقل المخزون الخاص بك إلى المستودع الآخر',
  'Transfer Stock Now': 'نقل المخزون الآن',
  'My Warehouse': 'مستودعاتي',
  'Add Warehouse': 'إضافة مستودع',
  'View map': 'عرض الخريطة',
  'Address': 'العنوان',
  'Price': 'السعر',
  'Temperature': 'درجة حرارة',
  'Used': 'المستخدم',
  'Reserved Space': 'المساحة المحجوزة',
  'Expired WH': 'تنتهي صلاحيته',
  'Upgrade Space': 'زيادة المساحة',
  'Dry': 'جاف',
  'Cold': 'بارد',
  'Freezing': 'متجمد',
  'Add New Warehouse': 'إضافة مستودع جديد',
  'Properties of the warehouse to be added to the warehouse list':
      'خصائص المستودع المراد إضافتها إلى قائمة المستودعات',
  'Space Needed': 'المساحة المطلوبة',
  '10 M²  = 12 wooden pallets': '10 م² = 12 طبلية خشبي',
  'Booking Date': 'تاريخ الحجز',
  'From': 'من',
  'To': 'الى',
  'Stock Type': 'نوع المخزون',
  'Continue': 'استمرار',
  'What type of material ?': 'ما نوع المادة؟',
  'Foodstuffs': 'مواد الغذائية',
  'Chemicals': 'مواد كيميائية',
  'Electrical materials': 'مواد كهربائية',
  'other': 'اخرى',
  'Type': 'النوع',
  'space': 'المساحة',
  'M²': 'م²',
  'Stock ID': 'معرف المخزون',
  'View Details': 'عرض التفاصيل',
  'Subscription ID': 'معرف الإشتراك',
  'Barcode': 'الباكود',
  'Unit': 'الوحدة',
  'The number': 'العدد',
  'Stock description': 'وصف المخزون',
  'Inventory Warehouse': 'مستودع المخزون',
  'Stock Inventory': 'المخزون',
  'Stock Warehouse': 'مستودع المخزون',
  'Enter Stock': 'أدخل مخزون',
  'Add Stock': 'إضافة مخزون',
  'Photo Gallery': 'معرض الصور',
  'Camera': 'كاميرا',
  'Name stock': 'اسم المخزون',
  'Barcode scanner (optional)': 'ماسح الباركود (اختياري)',
  'The space to be enter': 'المساحة المراد دخولها',
  'Note: The stock to be stored must be the same as the stored stock':
      'ملحوظة: المخزون المراد تخزينه يجب أن يكون نفس المخزون المخزن',
  'Stock transfer': 'نقل المخزون',
  'Description': 'الوصف',
  'The space to be transfer': 'المساحة المراد نقلها',
  'Transfer to': 'نقل الى',
  'Warehouse name': 'اسم المستودع',
  'Transfer': 'نقل',
  'Confirm location': 'تأكيد الموقع',
  'Withdraw Now': 'سحب الآن',
  'With packaging': 'مع التغليف',
  'Select a delivery location': 'حدد موقع التسليم',
  'With delivery to a new location': 'مع التسليم إلى موقع جديد',
  'Other services': 'خدمات أخرى',
  'Default: Receive from warehouse': 'الافتراضي: الاستلام من المستودع',
  'The space to be withdrawn': 'المساحة المراد سحبها',
  'Withdrawal date': 'تاريخ السحب',
  'Stock withdrawal': 'سحب المخزون',
  'Enter Now': 'أدخل الأن',
  'date': 'التاريخ',
  'Transfer now': 'نقل الآن',
  'Address WH': 'عنوان المستودع',
  'Locate inventory': 'حدد موقع المخزون',
  'Select the warehouse to continue': 'حدد المستودع للمتابعة',
  'continue': 'استمرار',
  'Search Location': 'بحث عن موقع',
  'change Inventory location': 'تغير موقع المخزون',
  'Locate inventory on the map': 'تحديد موقع المخزون على الخريطة',
  'Click on any location on the map to choose the inventory location':
      'قم بالضغط على اي موقع على الخريطة للاختيار موقع المخزون',
  'cancel': 'إلغاء',
  'Please select a inventory location': 'الرجاء تحديد موقع المخزون',
  'Locate your inventory on the map now':
      'قم بتحديد موقع المخزون على الخريطة الان',
  'Ok': 'موافق',
  'capacity': 'السعة',
  'phone': 'رقم الهاتف',
  'price Per Meter': 'السعر لكل متر',
  'Total price': 'السعر الاجمالي',
  'You have selected the inventory location': 'لقد قمت بتحديد موقع المخزون',
  'Confirm the operation': 'تأكيد العملية',
  'Do you want to store in the warehouse': 'هل تريد التخزين في المخزن',
  '?': '؟',
  'Warehouse details': 'تفاصيل المستودع',
  'the cost': 'التكلفة',
  'distance': 'المسافة',
  'Warehouse location': 'موقع المستودع',
  'Inventory location': 'موقع المخزون',
  'the map': 'الخريطة',
  'km': 'كم',
  'SR': 'ريال سعودي',
  'Pay now': 'ادفع الآن',
  'Warehouse rental period': 'فترة تأجير المستودعات',
  'Warehouse Features': 'مميزات المستودع',
  'Warehouse ID': 'معرف المستودع',
  'Invoice info': 'معلومات الفاتورة',
  'INVOICE': 'فاتورة',
  'invoice': 'فاتورة',
  'done': 'تم',
  'Profile': 'الملف الشخصي',
  'Settings': 'الاعدادات',
  'Personal Information': 'المعلومات شخصية',
  'Username': 'اسم المستخدم',
  'Business Name': 'الاسم التجاري',
  'Business Competence':'الكفاءة التجارية',
  'Subscription Ends':'ينتهي الاشتراك',
};
