const Map<String, String> en = {
  'Home': 'Home',
  'Inventory': 'Inventory',
  'Self management of inventory': 'Self management of inventory',
  'you can enter, withdraw, and transfer the inventory alone':
      'you can enter, withdraw, and transfer the inventory alone',
  'control panel': 'control panel',
  'call customer care': 'call customer care',
  'you can add your inventory by customer care':
      'you can add your inventory by customer care',
  'call now': 'call now',
  'Monitoring': 'Monitoring',
  'Account Monitoring': 'Account Monitoring',
  'Analysis of your inventory can be found':
      'Analysis of your inventory can be found',
  'view': 'view',
  'Start Adding Warehouse': 'Start Adding Warehouse',
  'Warehouse Management': 'Warehouse Management',
  'You can add warehouse and view warehouse list':
      'You can add warehouse and view warehouse list',
  'Enter Inventory': 'Enter Inventory',
  'Management Now': 'Management Now',
  'operations': 'operations',
  'Your inventory can be added to the warehouse':
      'Your inventory can be added to the warehouse',
  'Enter stock Now': 'Enter stock Now',
  'Withdrawal of inventory': 'Withdrawal of inventory',
  'You can withdraw your inventory from the warehouse':
      'You can withdraw your inventory from the warehouse',
  'Withdrawal Stock Now': 'Withdrawal Stock Now',
  'Transfer Inventory': 'Transfer Inventory',
  'You can transfer your inventory to the anther warehouse':
      'You can transfer your inventory to the anther warehouse',
  'Transfer Stock Now': 'Transfer Stock Now',
  'My Warehouse': 'My Warehouse',
  'Add Warehouse': 'Add Warehouse',
  'View map': 'View map',
  'Address': 'Address',
  'Price': 'Price',
  'Temperature': 'Temperature',
  'Used': 'Used',
  'Reserved Space': 'Reserved Space',
  'Expired WH': 'Expired WH',
  'Upgrade Space': 'Upgrade Space',
  'Dry': 'Dry',
  'Cold': 'Cold',
  'Freezing': 'Freezing',
  'Add New Warehouse': 'Add New Warehouse',
  'Properties of the warehouse to be added to the warehouse list':
      'Properties of the warehouse to be added to the warehouse list',
  'Space Needed': 'Space Needed',
  '10 M²  = 12 wooden pallets': '10 M²  = 12 wooden pallets',
  'Booking Date': 'Booking Date',
  'To': 'To',
  'From': 'From',
  'Stock Type': 'Stock Type',
  'Continue': 'Continue',
  'What type of material ?': 'What type of material ?',
  'Foodstuffs': 'Foodstuffs',
  'Chemicals': 'Chemicals',
  'Electrical materials': 'Electrical materials',
  'other': 'other',
  'Type': 'Type',
  'space': 'space',
  'M²': 'M²',
  'Stock ID': 'Stock ID',
  'View Details': 'View Details',
  'Subscription ID': 'Subscription ID',
  'Barcode': 'Barcode',
  'Unit': 'Unit',
  'The number': 'The number',
  'Stock description': 'Stock description',
  'Inventory Warehouse': 'Inventory Warehouse',
  'Stock Inventory': 'Stock Inventory',
  'Stock Warehouse': 'Stock Warehouse',
  'Enter Stock': 'Enter Stock',
  'Add Stock': 'Add Stock',
  'Photo Gallery': 'Photo Gallery',
  'Camera': 'Camera',
  'Name stock': 'Name stock',
  'Barcode scanner (optional)': 'Barcode scanner (optional)',
  'The space to be enter': 'The space to be enter',
  'Note: The stock to be stored must be the same as the stored stock':
      'Note: The stock to be stored must be the same as the stored stock',
  'Stock transfer': 'Stock transfer',
  'Description': 'Description',
  'The space to be transfer': 'The space to be transfer',
  'Transfer to': 'Transfer to',
  'Warehouse name': 'Warehouse name',
  'Transfer': 'Transfer',
  'Confirm location': 'Confirm location',
  'Withdraw Now': 'Withdraw Now',
  'With packaging': 'With packaging',
  'Select a delivery location': 'Select a delivery location',
  'With delivery to a new location': 'With delivery to a new location',
  'Other services': 'Other services',
  'Default: Receive from warehouse': 'Default: Receive from warehouse',
  'The space to be withdrawn': 'The space to be withdrawn',
  'Withdrawal date': 'Withdrawal date',
  'Stock withdrawal': 'Stock withdrawal',
  'Enter Now': 'Enter Now',
  'date': 'date',
  'Transfer now': 'Transfer now',
  'Address WH': 'Address WH',
  'Locate inventory': 'Locate inventory',
  'Select the warehouse to continue': 'Select the warehouse to continue',
  'continue': 'continue',
  'Search Location': 'Search Location',
  'change Inventory location': 'change Inventory location',
  'Locate inventory on the map': 'Locate inventory on the map',
  'Click on any location on the map to choose the inventory location':
      'Click on any location on the map to choose the inventory location',
  'cancel': 'cancel',
  'Please select a inventory location': 'Please select a inventory location',
  'Locate your inventory on the map now':
      'Locate your inventory on the map now',
  'Ok': 'Ok',
  'capacity': 'capacity',
  'phone': 'phone',
  'price Per Meter': 'price Per Meter',
  'Total price': 'Total price',
  'You have selected the inventory location':
      'You have selected the inventory location',
  'Confirm the operation':'Confirm the operation',
  'Do you want to store in the warehouse':'Do you want to store in the warehouse',
  '?':'?',
  'Warehouse details':'Warehouse details',
  'the cost':'the cost',
  'distance':'distance',
  'Warehouse location':'Warehouse location',
  'Inventory location':'Inventory location',
  'the map':'the map',
  'km':'km',
  'SR':'SR',
  'Pay now':'Pay now',
  'Warehouse rental period':'Warehouse rental period',
  'Warehouse Features':'Warehouse Features',
  'Warehouse ID':'Warehouse ID',
  'Invoice info':'Invoice info',
  'INVOICE':'INVOICE',
  'invoice':'invoice',
  'done':'done',
  'Profile':'Profile',
  'Settings':'Settings',
  'Personal Information':'Personal Information',
  'Username':'Username',
  'Business Name':'Business Name',
  'Business Competence':'Business Competence',
  'Subscription Ends':'Subscription Ends',



};
