const Map<String, String> en = {
  'Home': 'Home',
  'Inventory': 'Inventory',
  'Self management of inventory': 'Self management of inventory',
  'you can enter, withdraw, and transfer the inventory alone':
      'you can enter, withdraw, and transfer the inventory alone',
  'control panel': 'control panel',
  'call customer care': 'call customer care',
  'you can add your inventory by customer care':
      'you can add your inventory by customer care',
  'call now': 'call now',
  'Monitoring': 'Monitoring',
  'Account Monitoring': 'Account Monitoring',
  'Analysis of your inventory can be found':
      'Analysis of your inventory can be found',
  'view': 'view',
  'Start Adding Warehouse': 'Start Adding Warehouse',
  'Warehouse Management': 'Warehouse Management',
  'You can add warehouse and view warehouse list':
      'You can add warehouse and view warehouse list',
  'Enter Inventory': 'Enter Inventory',
  'Management Now': 'Management Now',
  'operations': 'operations',
  'Your inventory can be added to the warehouse':
      'Your inventory can be added to the warehouse',
  'Enter stock Now': 'Enter stock Now',
  'Withdrawal of inventory': 'Withdrawal of inventory',
  'You can withdraw your inventory from the warehouse':
      'You can withdraw your inventory from the warehouse',
  'Withdrawal Stock Now': 'Withdrawal Stock Now',
  'Transfer Inventory': 'Transfer Inventory',
  'You can transfer your inventory to the anther warehouse':
      'You can transfer your inventory to the anther warehouse',
  'Transfer Stock Now': 'Transfer Stock Now',
  'My Warehouse': 'My Warehouse',
  'Add Warehouse': 'Add Warehouse',
  'View map': 'View map',
  'Address': 'Address',
  'Price': 'Price',
  'Temperature': 'Temperature',
  'Used': 'Used',
  'Reserved Space': 'Reserved Space',
  'Expired WH': 'Expired WH',
  'Upgrade Space': 'Upgrade Space',
  'Dry': 'Dry',
  'Cold': 'Cold',
  'Freezing': 'Freezing',
  'Add New Warehouse': 'Add New Warehouse',
  'Properties of the warehouse to be added to the warehouse list':
      'Properties of the warehouse to be added to the warehouse list',
  'Space Needed': 'Space Needed',
  '10 M²  = 12 wooden pallets': '10 M²  = 12 wooden pallets',
  'Booking Date': 'Booking Date',
  'To': 'To',
  'From': 'From',
  'Stock Type': 'Stock Type',
  'Continue': 'Continue',
  'What type of material ?': 'What type of material ?',
  'Foodstuffs': 'Foodstuffs',
  'Chemicals': 'Chemicals',
  'Electrical materials': 'Electrical materials',
  'other': 'other',
  'Type': 'Type',
  'space': 'space',
  'M²': 'M²',
  'Stock ID': 'Stock ID',
  'View Details': 'View Details',
  'Subscription ID': 'Subscription ID',
  'Barcode': 'Barcode',
  'Unit': 'Unit',
  'The number': 'The number',
  'Stock description': 'Stock description',
  'Inventory Warehouse': 'Inventory Warehouse',
  'Stock Inventory': 'Stock Inventory',
  'Stock Warehouse': 'Stock Warehouse',
  'Enter Stock': 'Enter Stock',
  'Add Stock': 'Add Stock',
  'Photo Gallery': 'Photo Gallery',
  'Camera': 'Camera',
  'Name stock': 'Name stock',
  'Barcode scanner (optional)': 'Barcode scanner (optional)',
  'The space to be enter': 'The space to be enter',
  'Note: The stock to be stored must be the same as the stored stock':
      'Note: The stock to be stored must be the same as the stored stock',
  'Stock transfer': 'Stock transfer',
  'Description': 'Description',
  'The space to be transfer': 'The space to be transfer',
  'Transfer to': 'Transfer to',
  'Warehouse name': 'Warehouse name',
  'Transfer': 'Transfer',
  'Confirm location': 'Confirm location',
  'Withdraw Now': 'Withdraw Now',
  'With packaging': 'With packaging',
  'Select a delivery location': 'Select a delivery location',
  'With delivery to a new location': 'With delivery to a new location',
  'Other services': 'Other services',
  'Default: Receive from warehouse': 'Default: Receive from warehouse',
  'The space to be withdrawn': 'The space to be withdrawn',
  'Withdrawal date': 'Withdrawal date',
  'Stock withdrawal': 'Stock withdrawal',
  'Enter Now': 'Enter Now',
  'date': 'date',
  'Transfer now': 'Transfer now',
  'Address WH': 'Address WH',
  'Locate inventory': 'Locate inventory',
  'Select the warehouse to continue': 'Select the warehouse to continue',
  'continue': 'continue',
  'Search Location': 'Search Location',
  'change Inventory location': 'change Inventory location',
  'Locate inventory on the map': 'Locate inventory on the map',
  'Click on any location on the map to choose the inventory location':
      'Click on any location on the map to choose the inventory location',
  'cancel': 'cancel',
  'Please select a inventory location': 'Please select a inventory location',
  'Locate your inventory on the map now':
      'Locate your inventory on the map now',
  'Ok': 'Ok',
  'capacity': 'capacity',
  'phone': 'phone',
  'price Per Meter': 'price Per Meter',
  'Total price': 'Total price',
  'You have selected the inventory location':
      'You have selected the inventory location',
  'Confirm the operation': 'Confirm the operation',
  'Do you want to store in the warehouse':
      'Do you want to store in the warehouse',
  '?': '?',
  'Warehouse details': 'Warehouse details',
  'the cost': 'the cost',
  'distance': 'distance',
  'Warehouse location': 'Warehouse location',
  'Inventory location': 'Inventory location',
  'the map': 'the map',
  'km': 'km',
  'SR': 'SR',
  'Pay now': 'Pay now',
  'Warehouse rental period': 'Warehouse rental period',
  'Warehouse Features': 'Warehouse Features',
  'Warehouse ID': 'Warehouse ID',
  'Invoice info': 'Invoice info',
  'INVOICE': 'INVOICE',
  'invoice': 'invoice',
  'done': 'done',
  'Profile': 'Profile',
  'Settings': 'Settings',
  'Personal Information': 'Personal Information',
  'Username': 'Username',
  'Business Name': 'Business Name',
  'Business Competence': 'Business Competence',
  'Subscription Ends': 'Subscription Ends',
  'Transactions': 'Transactions',
  'Enter inventory': 'Enter inventory',
  'Enters': 'Enters',
  'Withdrawal': 'Withdrawal',
  'Withdrawals': 'Withdrawals',
  'All Transactions': 'All Transactions',
  'Transaction ID': 'Transaction ID',
  'Quantity': 'Quantity',
  'Under Review': 'Under Review',
  'Accepted': 'Accepted',
  'Rejected': 'Rejected',
  'Share': 'Share',
  'Please enter the date': 'Please enter the date',
  'Please enter the space you need': 'Please enter the space you need',
  'Contact Us': 'Contact Us',
  'Language': 'Language',
  'Delete Account': 'Delete Account',
  'Terms & Conditions': 'Terms & Conditions',
  'Sign Out': 'Sign Out',
  '* Of course, here is a definition of each point in the policy and terms of use of the mediation application between store owners and tenants:':
      '* Of course, here is a definition of each point in the policy and terms of use of the mediation application between store owners and tenants:',
  '1. Application definition:\n\n - The mediation application is an electronic platform that acts as an intermediary between store owners and tenants.\n\n The app allows warehouse owners to view information about their storage space and the services they provide, while tenants can search for suitable storage space and make reservations.\n\n 2. Registration and accounts:\n\n - All users must register their accounts in the application using personal information such as name and email address.\n\n - Users must provide accurate and correct information during the registration process to ensure smooth and effective communication.\n\n - Users must keep their account information confidential and not share it with any third party.\n\n 3. Rights and obligations:\n\n Store owners are obligated to provide accurate information about the store and the services provided, including prices and time frames.\n\n - Renters are obligated to comply with the terms and conditions applicable in the application, including the cancellation and compensation policy.\n\n 4. Booking and payment:\n\n - Tenants must make a reservation through the application and with the approval of the store owners for the reservation. Payment must be made via the payment methods available in the application, such as credit cards or electronic payment methods.\n\n - A commission will be collected from tenants when using the application services and will be paid to the store owners.\n\n 5. Insurance and liability:\n\n - The application may provide options for shipping and storage insurance. Users are responsible for choosing the insurance appropriate to their needs.\n\n - The application is not responsible for any damages or losses that occur during the use of the services provided on the platform.\n\n 6. Booking cancellation and refund:\n\n - Users must adhere to the reservation cancellation policy applicable in the application. A cancellation fee will apply to renters if a reservation is canceled after a certain period.\n\n 7. privacy policy:\n\n - The privacy policy outlines how we collect and use personal information in the application. Users must read and understand the privacy policy applicable to the application.\n\n 8. Account Termination:\n\n - The application has the right to terminate the account of any user who violates the terms and conditions or causes inconvenience to others. Account termination may include, for example, temporary or permanent suspension.\n\n 9. Change of terms and conditions:\n\n - The application may change the terms and conditions of use, and users will be notified of any potential changes through notifications or updates in the application.\n\n 10. Contact us:\n\n - Users should contact the app support team in case of any queries or issues while using the app.\n\n 11. Modify or cancel your reservation:\n\n - Renters can modify or cancel their reservations in accordance with the reservation modification and cancellation policy applicable in the application. A cancellation fee may apply to renters if a reservation is canceled after a certain period.\n\n 12. User Reviews:\n\n - Users can provide ratings and reviews for store owners and their services. Users must provide honest and constructive reviews to enhance the quality of the Services.\n\n 13. Information integrity:\n\n - Users should be careful when sharing sensitive information such as credit card information via the app. The application must have security measures to protect personal information.\n\n 14. Rulers violations:\n\n - Users must report any violations of the terms and conditions or security violations on the application. These reports will be investigated and necessary measures will be taken.\n\n 15. Local laws:\n\n - Users must comply with local laws and regulations applicable in their area when using the Application Services.\n\n 16. Compensation and responsibilities of both parties:\n\n - Tenants and store owners must reach a clear agreement regarding compensation in the event of any damages or losses occurring while using the services. The application is not responsible for any claims in this regard.\n\n 17. Cooperation with the authorities:\n\n - The application must cooperate with local authorities regarding investigations and information requested from it.\n\n 18. NOTICES AND COMMUNICATIONS:\n\n - The Application may send notifications and communications to users via email, text messages or other means for purposes such as platform updates and promotion of services.\n\n 19. Application of laws and disputes:\n\n In the event of any dispute between tenants and warehouse owners, the parties should try to resolve the dispute amicably first through communication and negotiation. If the dispute is not resolved amicably, the parties can resort to local laws and judicial system to resolve the dispute.\n\n 20. Updated policy and terms:\n\n The application development company reserves the right to amend or update the Terms and Conditions of Use. Users will be notified of any potential changes through the contact methods in the application':
      '1. Application definition:\n\n - The mediation application is an electronic platform that acts as an intermediary between store owners and tenants.\n\n The app allows warehouse owners to view information about their storage space and the services they provide, while tenants can search for suitable storage space and make reservations.\n\n 2. Registration and accounts:\n\n - All users must register their accounts in the application using personal information such as name and email address.\n\n - Users must provide accurate and correct information during the registration process to ensure smooth and effective communication.\n\n - Users must keep their account information confidential and not share it with any third party.\n\n 3. Rights and obligations:\n\n Store owners are obligated to provide accurate information about the store and the services provided, including prices and time frames.\n\n - Renters are obligated to comply with the terms and conditions applicable in the application, including the cancellation and compensation policy.\n\n 4. Booking and payment:\n\n - Tenants must make a reservation through the application and with the approval of the store owners for the reservation. Payment must be made via the payment methods available in the application, such as credit cards or electronic payment methods.\n\n - A commission will be collected from tenants when using the application services and will be paid to the store owners.\n\n 5. Insurance and liability:\n\n - The application may provide options for shipping and storage insurance. Users are responsible for choosing the insurance appropriate to their needs.\n\n - The application is not responsible for any damages or losses that occur during the use of the services provided on the platform.\n\n 6. Booking cancellation and refund:\n\n - Users must adhere to the reservation cancellation policy applicable in the application. A cancellation fee will apply to renters if a reservation is canceled after a certain period.\n\n 7. privacy policy:\n\n - The privacy policy outlines how we collect and use personal information in the application. Users must read and understand the privacy policy applicable to the application.\n\n 8. Account Termination:\n\n - The application has the right to terminate the account of any user who violates the terms and conditions or causes inconvenience to others. Account termination may include, for example, temporary or permanent suspension.\n\n 9. Change of terms and conditions:\n\n - The application may change the terms and conditions of use, and users will be notified of any potential changes through notifications or updates in the application.\n\n 10. Contact us:\n\n - Users should contact the app support team in case of any queries or issues while using the app.\n\n 11. Modify or cancel your reservation:\n\n - Renters can modify or cancel their reservations in accordance with the reservation modification and cancellation policy applicable in the application. A cancellation fee may apply to renters if a reservation is canceled after a certain period.\n\n 12. User Reviews:\n\n - Users can provide ratings and reviews for store owners and their services. Users must provide honest and constructive reviews to enhance the quality of the Services.\n\n 13. Information integrity:\n\n - Users should be careful when sharing sensitive information such as credit card information via the app. The application must have security measures to protect personal information.\n\n 14. Rulers violations:\n\n - Users must report any violations of the terms and conditions or security violations on the application. These reports will be investigated and necessary measures will be taken.\n\n 15. Local laws:\n\n - Users must comply with local laws and regulations applicable in their area when using the Application Services.\n\n 16. Compensation and responsibilities of both parties:\n\n - Tenants and store owners must reach a clear agreement regarding compensation in the event of any damages or losses occurring while using the services. The application is not responsible for any claims in this regard.\n\n 17. Cooperation with the authorities:\n\n - The application must cooperate with local authorities regarding investigations and information requested from it.\n\n 18. NOTICES AND COMMUNICATIONS:\n\n - The Application may send notifications and communications to users via email, text messages or other means for purposes such as platform updates and promotion of services.\n\n 19. Application of laws and disputes:\n\n In the event of any dispute between tenants and warehouse owners, the parties should try to resolve the dispute amicably first through communication and negotiation. If the dispute is not resolved amicably, the parties can resort to local laws and judicial system to resolve the dispute.\n\n 20. Updated policy and terms:\n\n The application development company reserves the right to amend or update the Terms and Conditions of Use. Users will be notified of any potential changes through the contact methods in the application',
  'Add Item':'Add Item',


};
